### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by teddyknox** [sigoden/aichat#54] opened 2023-03-09 14:46 UTC
I built version 0.5.0 from source on a mac. Using a free-tier API key but not getting any output. messages.md file shows no results when saving is on. Shouldn't it work with a free tier key? Or if not, shouldn't there be some error message?

**Comment by sigoden** [comment] 2023-03-09 14:58
run `aichat math 3 + 4`,  see if there is any output?

**Comment by sigoden** [comment] 2023-03-09 23:58
I can't reproduce the problem and lack of user feedback, close this issue.

**Comment by teddyknox** [comment] 2023-03-15 16:04
Please reopen, when I run this, I get no output

**Comment by teddyknox** [comment] 2023-03-15 16:07
Should `aichat` work with a free ChatGPT account?

**Comment by sigoden** [comment] 2023-03-15 23:54
There is no limitation on chatgpt account type.

Can you run the following code and screenshot the result?
```
aichat -V
aichat -S -H math 1 + 2
```

**Comment by sigoden** [comment] 2023-03-17 00:37
No feedback, so I  close the issue.

If you have any questions, you can continue asking.

**Closed by sigoden** 2023-03-17 00:37 UTC
